language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
   
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
          packages: 
            - clang-7.0
            - libstdc++-7-dev
          env:
            - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"
    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
    ############################################################################
    # Build main and tests
    ############################################################################

    - make
    
after_success:
    # todo
